# Generated by Django 5.2.3 on 2025-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_phone_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='title',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='car_model',
            field=models.CharField(default='Toyota Camry', max_length=100),
            preserve_default=False,
        ),
    ]
