# Generated by Django 5.2.3 on 2025-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_car_remove_carlisting_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlisting',
            old_name='daily_rate',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='carimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
