# Generated by Django 5.2.3 on 2025-06-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarListing',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='carimage',
            old_name='listing',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='listing',
            new_name='car',
        ),
    ]
